name: build and push the docker image 

on:
  push:
    branches: [ main ]
  
jobs:
  build-and-push:
    name: Build and Push ECR
    runs-on: ubuntu:latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials 
    used: aws-actions/configure-aws-credentials@v1
    with: 
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-2
      


   