name: Build and Push Image to AWS ECR
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build docker image
      run : docker build -t new:latest . 
    
    - name: Tag Docker image 
      run : docker tag new:latest 517061158972.dkr.ecr.us-east-2.amazonaws.com/docker
   
    - name: push docker image to ecr 
      run: |
        docker push 517061158972.dkr.ecr.us-east-2.amazonaws.com/docker