name: Dockerfile linter 

on: 
  workflow_dispatch:
    
jobs: 
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Update Pull Reuquest 
        uses: actions/github-script@v6
        if: github.event.name == 'pull_request'
        with:
          script: |
            const output = `
            ### Hadolist: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
            issues_number: context.issues.numer,
            owner: context.repo.owner,
            repo: context.repo.repo
            body: output
            })